apiVersion: v1
kind: Service
metadata:
  name: jenkins-pipeline-demo
  namespace: default
  labels:
    app: jenkins-pipeline-demo
spec:
  type: LoadBalancer
  selector:
    app: jenkins-pipeline-demo
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
